# Generated by Django 5.0.4 on 2024-08-18 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.IntegerField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateTimeField(auto_now=True)),
                ('OrderStatus', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.IntegerField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=50)),
                ('productDescription', models.CharField(max_length=500)),
                ('Price', models.IntegerField()),
                ('StockQuantity', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('StoreID', models.IntegerField(primary_key=True, serialize=False)),
                ('StoreName', models.CharField(max_length=50)),
                ('OwnerName', models.CharField(max_length=50)),
                ('StoreOwner', models.CharField(max_length=50)),
                ('PassWord', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Verifications', models.FileField(upload_to='')),
                ('logo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.IntegerField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('OrderItemID', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='StoreID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.AddField(
            model_name='order',
            name='StoreId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('RatingID', models.CharField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], max_length=200, primary_key=True, serialize=False)),
                ('ReviewgText', models.TextField(blank=True, max_length=500, null=True)),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.user')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.user'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('FavoriteID', models.IntegerField(primary_key=True, serialize=False)),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.user')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('ComplaintId', models.IntegerField(primary_key=True, serialize=False)),
                ('ComplaintDate', models.DateTimeField()),
                ('ComplaintText', models.IntegerField()),
                ('Status', models.CharField(max_length=50)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.user')),
            ],
        ),
    ]
