# Generated by Django 5.0.4 on 2024-08-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='Category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
