# Generated by Django 5.0.4 on 2024-08-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='Verifications',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
