# Generated by Django 5.0.4 on 2024-09-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_store_verifications_alter_store_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
